---
driver:
  name:         vagrant
  provision: true

provisioner:
  name:         chef_zero

platforms:
  - name:       centos-6.9
  - name:       centos-7.4


suites:
  - name:       default-server
    driver_config:
        network:
          - ["private_network", { ip: "192.168.33.53" }]
    run_list:
      - recipe[iptables]
      - recipe[nfs::server]
      - recipe[wma_nfs::create_exports]
      - recipe[wma_nfs::iptables_create]
    attributes: {
      "wma" :   {
        "nfs" : {
          "exports" : [
            {
              "export" : "/usr/local/share",
              "ip_range" : "*",
              "options" : [ "rw", "nohide", "insecure", "async", "no_root_squash", "no_subtree_check" ],
              "writeable" : true,
              "sync" : true
            }
          ]
        }
      }
    }
  - name:       default-client
    run_list:
      - recipe[iptables]
      - recipe[nfs::client4]
      - recipe[wma_nfs::create_mount]
    driver:
      network:
        - ['private_network', {ip: '192.168.33.63'}]
    attributes: {
      "wma" :   {
        "nfs" : {
          "mounts" : [
            {
              "export" : "/usr/local/share/nfs",
              "device" : "192.168.33.53:/usr/local/share",
              "fstype" : "nfs",
              "options" : ["rw","soft","intr"]

            }
          ]
        }
      }
    }
